version: "3.1"
services:
  zanatadb:
    image: "mariadb:10.3.2"
    restart: always
    container_name: "zanatadb"
    command: "--character-set-server=utf8 --collation-server=utf8_general_ci"
    volumes:
      - zanata-db:/var/lib/mysql:Z
    environment: 
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_USER: "${ZANATA_MYSQL_USER}"
      MYSQL_PASSWORD: "${ZANATA_MYSQL_PASSWORD}"
      MYSQL_DATABASE: "${ZANATA_MYSQL_DATABASE}"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--silent"]
  zanataapp:
    image: "zanata/server:4.3.1"
    container_name: "zanataapp"
    ports:
      - "8080:8080"
    volumes:
      - zanata-files:/var/lib/zanata
    links:
      - zanatadb
    depends_on:
      - zanatadb
    environment:
      ZANATA_HOME: "/var/lib/zanata"
      DB_HOSTNAME: "zanatadb"
      DB_SCHEMA: "${ZANATA_MYSQL_DATABASE}"
      DB_USERNAME: "${ZANATA_MYSQL_USER}"
      DB_PASSWORD: "${ZANATA_MYSQL_PASSWORD}"
volumes:
  zanata-db:
  zanata-files:
